name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PYTHON_VERSION: 3.11

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run the pre-commit
        uses: pre-commit/action@v3.0.1

  testing:
    runs-on: ubuntu-latest
    container:
      image: htcondor/mini
      env:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/submituser/.local/bin
    steps:
      - uses: actions/checkout@v3

      - name: Install Python and more yum
        run: |
          yum install -y python${{ env.PYTHON_VERSION }}
          yum install -y python${{ env.PYTHON_VERSION }}-pip
          yum install -y python${{ env.PYTHON_VERSION }}-devel
          yum install -y gcc

      - name: HTCondor master
        run:  condor_master

      - name: Test submit to HTCondor
        run: su -c "condor_submit tests/sleep.sub" submituser

      - name: Install poetry
        run: su -c "pip${{ env.PYTHON_VERSION }} install poetry" submituser

      - name: Determine dependencies
        run: su -c "poetry lock" submituser

      - name: Install dependencies
        run: su -c "poetry install" submituser

      - name: Run pytest
        run: su -c "poetry run coverage run -m pytest tests/ -vvv" submituser

      - name: Check HTCondor logs
        run: |
          ls  /tmp/pytest-of-submituser/pytest-0/test_simple_workflow0/simple/.snakemake/htcondor
          for file in /tmp/pytest-of-submituser/pytest-0/test_simple_workflow0/simple/.snakemake/htcondor/*.log; do cat "$file"; done

      - name: Check HTCondor errors
        run: |
          ls  /tmp/pytest-of-submituser/pytest-0/test_simple_workflow0/simple/.snakemake/htcondor
          for file in /tmp/pytest-of-submituser/pytest-0/test_simple_workflow0/simple/.snakemake/htcondor/*.err; do cat "$file"; done

      - name: Run Coverage
        run: su -c "poetry run coverage report -m --omit=Snakefile" submituser
